//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPClient.SenecaES {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBase", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.EmployeeBase2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.EmployeeBase3))]
    public partial class EmployeeBase : SOAPClient.SenecaES.EmployeeAdd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeAdd", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.EmployeeBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.EmployeeBase2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.EmployeeBase3))]
    public partial class EmployeeAdd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBase2", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.EmployeeBase3))]
    public partial class EmployeeBase2 : SOAPClient.SenecaES.EmployeeBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPClient.SenecaES.EmployeeBase[] EmployeesSupervisedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPClient.SenecaES.EmployeeBase ReportsToEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReportsToEmployeeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPClient.SenecaES.EmployeeBase[] EmployeesSupervised {
            get {
                return this.EmployeesSupervisedField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesSupervisedField, value) != true)) {
                    this.EmployeesSupervisedField = value;
                    this.RaisePropertyChanged("EmployeesSupervised");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPClient.SenecaES.EmployeeBase ReportsToEmployee {
            get {
                return this.ReportsToEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsToEmployeeField, value) != true)) {
                    this.ReportsToEmployeeField = value;
                    this.RaisePropertyChanged("ReportsToEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReportsToEmployeeId {
            get {
                return this.ReportsToEmployeeIdField;
            }
            set {
                if ((this.ReportsToEmployeeIdField.Equals(value) != true)) {
                    this.ReportsToEmployeeIdField = value;
                    this.RaisePropertyChanged("ReportsToEmployeeId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBase3", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    public partial class EmployeeBase3 : SOAPClient.SenecaES.EmployeeBase2 {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPClient.SenecaES.AddressBase HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPClient.SenecaES.JobDutyBase[] JobDutiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPClient.SenecaES.AddressBase WorkAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPClient.SenecaES.AddressBase HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPClient.SenecaES.JobDutyBase[] JobDuties {
            get {
                return this.JobDutiesField;
            }
            set {
                if ((object.ReferenceEquals(this.JobDutiesField, value) != true)) {
                    this.JobDutiesField = value;
                    this.RaisePropertyChanged("JobDuties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPClient.SenecaES.AddressBase WorkAddress {
            get {
                return this.WorkAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAddressField, value) != true)) {
                    this.WorkAddressField = value;
                    this.RaisePropertyChanged("WorkAddress");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressBase", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    public partial class AddressBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityAndProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityAndProvince {
            get {
                return this.CityAndProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.CityAndProvinceField, value) != true)) {
                    this.CityAndProvinceField = value;
                    this.RaisePropertyChanged("CityAndProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobDutyBase", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    public partial class JobDutyBase : SOAPClient.SenecaES.JobDutyAdd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobDutyAdd", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.JobDutyBase))]
    public partial class JobDutyAdd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SenecaES.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/HelloWorld", ReplyAction="http://tempuri.org/IEmployeeService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/HelloWorld", ReplyAction="http://tempuri.org/IEmployeeService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AllEmployees", ReplyAction="http://tempuri.org/IEmployeeService/AllEmployeesResponse")]
        SOAPClient.SenecaES.EmployeeBase[] AllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AllEmployees", ReplyAction="http://tempuri.org/IEmployeeService/AllEmployeesResponse")]
        System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase[]> AllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeByIdResponse")]
        SOAPClient.SenecaES.EmployeeBase3 EmployeeById(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeByIdResponse")]
        System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase3> EmployeeByIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        SOAPClient.SenecaES.EmployeeBase AddEmployee(SOAPClient.SenecaES.EmployeeAdd newItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase> AddEmployeeAsync(SOAPClient.SenecaES.EmployeeAdd newItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : SOAPClient.SenecaES.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<SOAPClient.SenecaES.IEmployeeService>, SOAPClient.SenecaES.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public SOAPClient.SenecaES.EmployeeBase[] AllEmployees() {
            return base.Channel.AllEmployees();
        }
        
        public System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase[]> AllEmployeesAsync() {
            return base.Channel.AllEmployeesAsync();
        }
        
        public SOAPClient.SenecaES.EmployeeBase3 EmployeeById(System.Nullable<int> id) {
            return base.Channel.EmployeeById(id);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase3> EmployeeByIdAsync(System.Nullable<int> id) {
            return base.Channel.EmployeeByIdAsync(id);
        }
        
        public SOAPClient.SenecaES.EmployeeBase AddEmployee(SOAPClient.SenecaES.EmployeeAdd newItem) {
            return base.Channel.AddEmployee(newItem);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase> AddEmployeeAsync(SOAPClient.SenecaES.EmployeeAdd newItem) {
            return base.Channel.AddEmployeeAsync(newItem);
        }
    }
}
